debug: false
CameraMount: [0.12,0,0]
Camera2RgbExtincs: [0.015,0,0]
InflateSize: 0.7
MinDt: 0.15         #enlarge this param will cause latency but may improve precision
StaticPclLength: 2000
KFLifeTime: 0.8
MaxVel: 3
MapResolution: 0.2
IfBuildMap: false
WorldFrame: "map"
#CameraIntrinsics: [343.4963684082031, 343.4963684082031,320.0,180.0]
